alter table public.contact_messages
  add column if not exists admin_notes text not null default '';

create table if not exists public.income_entries (
  id bigint generated by default as identity primary key,
  concept text not null,
  category text not null default 'General',
  customer_name text,
  amount numeric(10, 2) not null check (amount >= 0),
  currency text not null default 'MXN',
  status text not null default 'received' check (status in ('pending', 'received', 'refunded', 'cancelled')),
  payment_date date not null,
  due_date date,
  payment_method text,
  reference_code text,
  source_type text not null default 'manual' check (source_type in ('manual', 'booking')),
  booking_id uuid unique references public.bookings (id) on delete set null,
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_income_entries_payment_date on public.income_entries (payment_date);
create index if not exists idx_income_entries_status on public.income_entries (status);
create index if not exists idx_income_entries_booking_id on public.income_entries (booking_id);

drop trigger if exists set_income_entries_updated_at on public.income_entries;
create trigger set_income_entries_updated_at
before update on public.income_entries
for each row execute procedure public.set_current_timestamp_updated_at();

alter table public.income_entries enable row level security;

drop policy if exists "Admins manage income entries" on public.income_entries;
create policy "Admins manage income entries"
on public.income_entries
for all
using (public.is_admin())
with check (public.is_admin());

create or replace function public.confirm_booking_payment(
  p_booking_id uuid,
  p_stripe_payment_intent text,
  p_raw_session jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.bookings%rowtype;
begin
  select *
    into v_booking
    from public.bookings
   where id = p_booking_id
   for update;

  if not found then
    raise exception 'Reserva no encontrada';
  end if;

  if v_booking.payment_status = 'paid' then
    return jsonb_build_object('ok', true, 'booking_id', v_booking.id);
  end if;

  update public.departures
     set booked_count = booked_count + v_booking.seats_reserved,
         status = case
           when booked_count + v_booking.seats_reserved >= capacity then 'sold_out'
           else status
         end,
         updated_at = timezone('utc', now())
   where id = v_booking.departure_id
     and booked_count + v_booking.seats_reserved <= capacity;

  if not found then
    raise exception 'No hay cupo suficiente para confirmar esta reserva';
  end if;

  update public.bookings
     set status = 'confirmed',
         payment_status = 'paid',
         stripe_payment_intent = coalesce(p_stripe_payment_intent, stripe_payment_intent),
         paid_at = timezone('utc', now()),
         checkout_payload = coalesce(checkout_payload, '{}'::jsonb) || jsonb_build_object('session', p_raw_session),
         updated_at = timezone('utc', now())
   where id = v_booking.id;

  insert into public.income_entries (
    concept,
    category,
    customer_name,
    amount,
    currency,
    status,
    payment_date,
    payment_method,
    reference_code,
    source_type,
    booking_id,
    notes
  )
  values (
    'Reserva pagada: ' || coalesce(v_booking.trip_title_snapshot, 'Viaje'),
    'Reservas',
    v_booking.customer_name,
    v_booking.total_amount,
    'MXN',
    'received',
    timezone('utc', now())::date,
    'Stripe / Confirmacion manual',
    p_stripe_payment_intent,
    'booking',
    v_booking.id,
    'Ingreso generado automaticamente para la salida del ' || coalesce(v_booking.departure_date_snapshot::text, 'viaje sin fecha')
  )
  on conflict (booking_id) do update
  set concept = excluded.concept,
      category = excluded.category,
      customer_name = excluded.customer_name,
      amount = excluded.amount,
      currency = excluded.currency,
      status = excluded.status,
      payment_date = excluded.payment_date,
      payment_method = excluded.payment_method,
      reference_code = excluded.reference_code,
      source_type = excluded.source_type,
      notes = excluded.notes,
      updated_at = timezone('utc', now());

  return jsonb_build_object('ok', true, 'booking_id', v_booking.id);
end;
$$;
