create table if not exists public.expense_entries (
  id bigint generated by default as identity primary key,
  concept text not null,
  category text not null default 'Operacion',
  vendor_name text,
  amount numeric(10, 2) not null check (amount >= 0),
  currency text not null default 'MXN',
  status text not null default 'paid' check (status in ('planned', 'paid', 'cancelled', 'refunded')),
  expense_date date not null,
  due_date date,
  payment_method text,
  reference_code text,
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_expense_entries_expense_date on public.expense_entries (expense_date);
create index if not exists idx_expense_entries_status on public.expense_entries (status);

drop trigger if exists set_expense_entries_updated_at on public.expense_entries;
create trigger set_expense_entries_updated_at
before update on public.expense_entries
for each row execute procedure public.set_current_timestamp_updated_at();

alter table public.expense_entries enable row level security;

drop policy if exists "Admins manage expense entries" on public.expense_entries;
create policy "Admins manage expense entries"
on public.expense_entries
for all
using (public.is_admin())
with check (public.is_admin());
