create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  phone text,
  is_admin boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  company_name text not null default 'Jalisco Rutas',
  hero_badge text not null default 'Salidas semanales desde Guadalajara y ZMG',
  hero_title text not null default 'Viajes y rutas turisticas con cupo real y apartado rapido',
  hero_subtitle text not null default 'Convierte visitas en reservas con una pagina informativa, catalogo vivo y atencion inmediata por WhatsApp.',
  support_email text not null default 'hola@jalisconrutas.com',
  support_phone text not null default '+52 33 1246 9036',
  whatsapp_number text not null default '523312469036',
  whatsapp_message text not null default 'Hola, quiero informacion sobre los proximos viajes y rutas turisticas.',
  chatbot_enabled boolean not null default false,
  chatbot_embed_code text not null default '',
  homepage_content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  destination text not null,
  meeting_point text not null,
  duration_text text not null,
  price numeric(10, 2) not null check (price >= 0),
  hero_image_url text,
  short_description text not null,
  description text not null,
  includes jsonb not null default '[]'::jsonb,
  itinerary jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.departures (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips (id) on delete cascade,
  departure_date date not null,
  return_date date,
  capacity integer not null check (capacity > 0),
  booked_count integer not null default 0 check (booked_count >= 0),
  promo_price numeric(10, 2) check (promo_price >= 0),
  status text not null default 'open' check (status in ('open', 'sold_out', 'cancelled')),
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  trip_id bigint not null references public.trips (id) on delete restrict,
  departure_id bigint not null references public.departures (id) on delete restrict,
  trip_title_snapshot text not null,
  departure_date_snapshot date not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  seats_reserved integer not null check (seats_reserved > 0),
  total_amount numeric(10, 2) not null check (total_amount >= 0),
  status text not null default 'pending_payment' check (status in ('pending_payment', 'confirmed', 'cancelled', 'refunded')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid', 'refunded')),
  stripe_session_id text unique,
  stripe_payment_intent text,
  checkout_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  message text not null,
  admin_notes text not null default '',
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.income_entries (
  id bigint generated by default as identity primary key,
  concept text not null,
  category text not null default 'General',
  customer_name text,
  amount numeric(10, 2) not null check (amount >= 0),
  currency text not null default 'MXN',
  status text not null default 'received' check (status in ('pending', 'received', 'refunded', 'cancelled')),
  payment_date date not null,
  due_date date,
  payment_method text,
  reference_code text,
  source_type text not null default 'manual' check (source_type in ('manual', 'booking')),
  booking_id uuid unique references public.bookings (id) on delete set null,
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email))
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_admin = true
  );
$$;

create or replace function public.confirm_booking_payment(
  p_booking_id uuid,
  p_stripe_payment_intent text,
  p_raw_session jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.bookings%rowtype;
begin
  select *
    into v_booking
    from public.bookings
   where id = p_booking_id
   for update;

  if not found then
    raise exception 'Reserva no encontrada';
  end if;

  if v_booking.payment_status = 'paid' then
    return jsonb_build_object('ok', true, 'booking_id', v_booking.id);
  end if;

  update public.departures
     set booked_count = booked_count + v_booking.seats_reserved,
         status = case
           when booked_count + v_booking.seats_reserved >= capacity then 'sold_out'
           else status
         end,
         updated_at = timezone('utc', now())
   where id = v_booking.departure_id
     and booked_count + v_booking.seats_reserved <= capacity;

  if not found then
    raise exception 'No hay cupo suficiente para confirmar esta reserva';
  end if;

  update public.bookings
     set status = 'confirmed',
         payment_status = 'paid',
         stripe_payment_intent = coalesce(p_stripe_payment_intent, stripe_payment_intent),
         paid_at = timezone('utc', now()),
         checkout_payload = coalesce(checkout_payload, '{}'::jsonb) || jsonb_build_object('session', p_raw_session),
         updated_at = timezone('utc', now())
   where id = v_booking.id;

  insert into public.income_entries (
    concept,
    category,
    customer_name,
    amount,
    currency,
    status,
    payment_date,
    payment_method,
    reference_code,
    source_type,
    booking_id,
    notes
  )
  values (
    'Reserva pagada: ' || coalesce(v_booking.trip_title_snapshot, 'Viaje'),
    'Reservas',
    v_booking.customer_name,
    v_booking.total_amount,
    'MXN',
    'received',
    timezone('utc', now())::date,
    'Stripe / Confirmacion manual',
    p_stripe_payment_intent,
    'booking',
    v_booking.id,
    'Ingreso generado automaticamente para la salida del ' || coalesce(v_booking.departure_date_snapshot::text, 'viaje sin fecha')
  )
  on conflict (booking_id) do update
  set concept = excluded.concept,
      category = excluded.category,
      customer_name = excluded.customer_name,
      amount = excluded.amount,
      currency = excluded.currency,
      status = excluded.status,
      payment_date = excluded.payment_date,
      payment_method = excluded.payment_method,
      reference_code = excluded.reference_code,
      source_type = excluded.source_type,
      notes = excluded.notes,
      updated_at = timezone('utc', now());

  return jsonb_build_object('ok', true, 'booking_id', v_booking.id);
end;
$$;

create index if not exists idx_trips_published on public.trips (published);
create index if not exists idx_departures_trip_id on public.departures (trip_id);
create index if not exists idx_departures_departure_date on public.departures (departure_date);
create index if not exists idx_bookings_departure_id on public.bookings (departure_id);
create index if not exists idx_contact_messages_status on public.contact_messages (status);
create index if not exists idx_income_entries_payment_date on public.income_entries (payment_date);
create index if not exists idx_income_entries_status on public.income_entries (status);
create index if not exists idx_income_entries_booking_id on public.income_entries (booking_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_trips_updated_at on public.trips;
create trigger set_trips_updated_at
before update on public.trips
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_departures_updated_at on public.departures;
create trigger set_departures_updated_at
before update on public.departures
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_bookings_updated_at on public.bookings;
create trigger set_bookings_updated_at
before update on public.bookings
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_contact_messages_updated_at on public.contact_messages;
create trigger set_contact_messages_updated_at
before update on public.contact_messages
for each row execute procedure public.set_current_timestamp_updated_at();

drop trigger if exists set_income_entries_updated_at on public.income_entries;
create trigger set_income_entries_updated_at
before update on public.income_entries
for each row execute procedure public.set_current_timestamp_updated_at();

alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.trips enable row level security;
alter table public.departures enable row level security;
alter table public.bookings enable row level security;
alter table public.contact_messages enable row level security;
alter table public.income_entries enable row level security;

drop policy if exists "Profiles read own or admin" on public.profiles;
create policy "Profiles read own or admin"
on public.profiles
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Profiles update own or admin" on public.profiles;
create policy "Profiles update own or admin"
on public.profiles
for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Public can read settings" on public.site_settings;
create policy "Public can read settings"
on public.site_settings
for select
using (true);

drop policy if exists "Admins manage settings" on public.site_settings;
create policy "Admins manage settings"
on public.site_settings
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read published trips" on public.trips;
create policy "Public can read published trips"
on public.trips
for select
using (published = true);

drop policy if exists "Admins manage trips" on public.trips;
create policy "Admins manage trips"
on public.trips
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read open departures" on public.departures;
create policy "Public can read open departures"
on public.departures
for select
using (
  status = 'open'
  and exists (
    select 1
      from public.trips
     where public.trips.id = public.departures.trip_id
       and public.trips.published = true
  )
);

drop policy if exists "Admins manage departures" on public.departures;
create policy "Admins manage departures"
on public.departures
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins manage bookings" on public.bookings;
create policy "Admins manage bookings"
on public.bookings
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public inserts contact messages" on public.contact_messages;
create policy "Public inserts contact messages"
on public.contact_messages
for insert
with check (true);

drop policy if exists "Admins manage contact messages" on public.contact_messages;
create policy "Admins manage contact messages"
on public.contact_messages
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins manage income entries" on public.income_entries;
create policy "Admins manage income entries"
on public.income_entries
for all
using (public.is_admin())
with check (public.is_admin());

insert into public.site_settings (
  id,
  company_name,
  hero_badge,
  hero_title,
  hero_subtitle,
  support_email,
  support_phone,
  whatsapp_number,
  whatsapp_message
)
values (
  1,
  'Jalisco Rutas',
  'Salidas semanales desde Guadalajara y ZMG',
  'Viajes y rutas turisticas con cupo real y apartado rapido',
  'Convierte visitas en reservas con una pagina informativa, catalogo vivo y atencion inmediata por WhatsApp.',
  'hola@jalisconrutas.com',
  '+52 33 1246 9036',
  '523312469036',
  'Hola, quiero informacion sobre los proximos viajes y rutas turisticas.'
)
on conflict (id) do nothing;

insert into public.trips (
  slug,
  title,
  destination,
  meeting_point,
  duration_text,
  price,
  short_description,
  description,
  includes,
  itinerary,
  tags,
  featured,
  published
)
values
  (
    'ruta-tequila-premium',
    'Ruta del Tequila Premium',
    'Tequila, Jalisco',
    'Glorieta Minerva, Guadalajara',
    '1 dia / 10 horas',
    1090,
    'Experiencia de un dia con enfoque en cultura, degustacion y tiempo libre.',
    'Salida ideal para publico local de Guadalajara que busca una experiencia rapida, bien organizada y facil de reservar.',
    '["Transporte redondo","Coordinador de viaje","Recorrido guiado","Tiempo libre"]'::jsonb,
    '["Salida desde Guadalajara","Recorrido por Tequila","Tiempo para comer","Regreso por la tarde"]'::jsonb,
    '["Fin de semana","Cultura","Parejas"]'::jsonb,
    true,
    true
  ),
  (
    'mazamitla-bosque',
    'Mazamitla y Bosque Encantado',
    'Mazamitla, Jalisco',
    'Plaza del Sol, Zapopan',
    '1 dia / ruta familiar',
    850,
    'Pueblo magico, aire libre y actividades ligeras para grupos y familias.',
    'Producto ideal para campanas frecuentes de venta por redes sociales y clientes que quieren escapadas cortas.',
    '["Transporte","Coordinacion","Paradas panoramicas","Tiempo libre"]'::jsonb,
    '["Salida temprano","Centro de Mazamitla","Bosque y miradores","Regreso"]'::jsonb,
    '["Naturaleza","Familiar","Pueblo magico"]'::jsonb,
    false,
    true
  ),
  (
    'chapala-ajijic-atardecer',
    'Chapala y Ajijic Atardecer',
    'Chapala y Ajijic',
    'Forum Tlaquepaque',
    '1 dia / paseo panoramico',
    790,
    'Salida accesible y atractiva para parejas y grupos pequenos.',
    'Una opcion de ticket accesible para mover volumen semanal desde Guadalajara y la Zona Metropolitana.',
    '["Transporte","Acompanamiento","Parada fotografica","Tiempo libre"]'::jsonb,
    '["Salida desde Tlaquepaque","Malecon de Chapala","Recorrido en Ajijic","Regreso al atardecer"]'::jsonb,
    '["Relax","Accesible","Parejas"]'::jsonb,
    false,
    true
  )
on conflict (slug) do nothing;

insert into public.departures (trip_id, departure_date, return_date, capacity, booked_count, promo_price, status, notes)
values
  ((select id from public.trips where slug = 'ruta-tequila-premium'), current_date + 7, current_date + 7, 18, 5, 890, 'open', 'Salida ideal para pauta en redes el fin de semana.'),
  ((select id from public.trips where slug = 'mazamitla-bosque'), current_date + 14, current_date + 14, 20, 8, 760, 'open', 'Ruta con enfoque familiar.'),
  ((select id from public.trips where slug = 'chapala-ajijic-atardecer'), current_date + 21, current_date + 21, 16, 4, 690, 'open', 'Salida accesible para captar nuevos clientes.');





