create table if not exists public.site_visitors (
  id bigint generated by default as identity primary key,
  visitor_token text not null unique,
  visit_count integer not null default 1,
  user_agent text,
  ip_address text,
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_site_visitors_last_seen_at on public.site_visitors (last_seen_at);

alter table public.site_visitors enable row level security;

drop policy if exists "Admins manage site visitors" on public.site_visitors;
create policy "Admins manage site visitors"
on public.site_visitors
for all
using (public.is_admin())
with check (public.is_admin());
